//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 增加自定义颜色... 的本地化字符串。
        /// </summary>
        internal static string AddCustomColor {
            get {
                return ResourceManager.GetString("AddCustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加16进制颜色... 的本地化字符串。
        /// </summary>
        internal static string AddCustomHexColor {
            get {
                return ResourceManager.GetString("AddCustomHexColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功加入到字典 的本地化字符串。
        /// </summary>
        internal static string AddCustomWordSuccess {
            get {
                return ResourceManager.GetString("AddCustomWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入到字典 的本地化字符串。
        /// </summary>
        internal static string AddToDictionary {
            get {
                return ResourceManager.GetString("AddToDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你尝试粘帖的内容包含了MS Word格式定义，\n你是否需要清楚这些格式? 的本地化字符串。
        /// </summary>
        internal static string AskWordCleaning {
            get {
                return ResourceManager.GetString("AskWordCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string CancelTable {
            get {
                return ResourceManager.GetString("CancelTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元属性 的本地化字符串。
        /// </summary>
        internal static string CellProperties {
            get {
                return ResourceManager.GetString("CellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择单元格再设置其属性 的本地化字符串。
        /// </summary>
        internal static string CellWarning {
            get {
                return ResourceManager.GetString("CellWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手工变更 的本地化字符串。
        /// </summary>
        internal static string ChangeWordString {
            get {
                return ResourceManager.GetString("ChangeWordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSS类 的本地化字符串。
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除所有HTML标签 的本地化字符串。
        /// </summary>
        internal static string ClearAllHtmlTags {
            get {
                return ResourceManager.GetString("ClearAllHtmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除CSS样式表 的本地化字符串。
        /// </summary>
        internal static string ClearCssFormatting {
            get {
                return ResourceManager.GetString("ClearCssFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除Font标签 的本地化字符串。
        /// </summary>
        internal static string ClearFontTags {
            get {
                return ResourceManager.GetString("ClearFontTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除格式 的本地化字符串。
        /// </summary>
        internal static string ClearFormatting {
            get {
                return ResourceManager.GetString("ClearFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除Span标签 的本地化字符串。
        /// </summary>
        internal static string ClearSpanTags {
            get {
                return ResourceManager.GetString("ClearSpanTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除样式 的本地化字符串。
        /// </summary>
        internal static string ClearStyle {
            get {
                return ResourceManager.GetString("ClearStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除Microsoft Word格式 的本地化字符串。
        /// </summary>
        internal static string ClearWordFormatting {
            get {
                return ResourceManager.GetString("ClearWordFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拼写已更新 的本地化字符串。
        /// </summary>
        internal static string CorrectSpelling {
            get {
                return ResourceManager.GetString("CorrectSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建链接 的本地化字符串。
        /// </summary>
        internal static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对话框工具条 的本地化字符串。
        /// </summary>
        internal static string DialogToolbar {
            get {
                return ResourceManager.GetString("DialogToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下拉框工具条 的本地化字符串。
        /// </summary>
        internal static string DropdownToolbar {
            get {
                return ResourceManager.GetString("DropdownToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增强编辑工具条 的本地化字符串。
        /// </summary>
        internal static string EnhancedEditToolbar {
            get {
                return ResourceManager.GetString("EnhancedEditToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件.. 的本地化字符串。
        /// </summary>
        internal static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为... 的本地化字符串。
        /// </summary>
        internal static string FileSaveAs {
            get {
                return ResourceManager.GetString("FileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按扭 的本地化字符串。
        /// </summary>
        internal static string FormButton {
            get {
                return ResourceManager.GetString("FormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多选框 的本地化字符串。
        /// </summary>
        internal static string FormCheckbox {
            get {
                return ResourceManager.GetString("FormCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单 的本地化字符串。
        /// </summary>
        internal static string FormForm {
            get {
                return ResourceManager.GetString("FormForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐含 的本地化字符串。
        /// </summary>
        internal static string FormHidden {
            get {
                return ResourceManager.GetString("FormHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口令 的本地化字符串。
        /// </summary>
        internal static string FormPassword {
            get {
                return ResourceManager.GetString("FormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单选框 的本地化字符串。
        /// </summary>
        internal static string FormRadio {
            get {
                return ResourceManager.GetString("FormRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string FormReset {
            get {
                return ResourceManager.GetString("FormReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string FormSelect {
            get {
                return ResourceManager.GetString("FormSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        internal static string FormSubmit {
            get {
                return ResourceManager.GetString("FormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框 的本地化字符串。
        /// </summary>
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本区 的本地化字符串。
        /// </summary>
        internal static string FormTextarea {
            get {
                return ResourceManager.GetString("FormTextarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML模式 的本地化字符串。
        /// </summary>
        internal static string HtmlMode {
            get {
                return ResourceManager.GetString("HtmlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部忽略 的本地化字符串。
        /// </summary>
        internal static string IgnoreAllString {
            get {
                return ResourceManager.GetString("IgnoreAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略 的本地化字符串。
        /// </summary>
        internal static string IgnoreString {
            get {
                return ResourceManager.GetString("IgnoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择图象后设置其image map属性 的本地化字符串。
        /// </summary>
        internal static string ImageMapWarning {
            get {
                return ResourceManager.GetString("ImageMapWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML缩进 的本地化字符串。
        /// </summary>
        internal static string IndentHtml {
            get {
                return ResourceManager.GetString("IndentHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入 的本地化字符串。
        /// </summary>
        internal static string InsertToolbar {
            get {
                return ResourceManager.GetString("InsertToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主工具条 的本地化字符串。
        /// </summary>
        internal static string MainToolbar {
            get {
                return ResourceManager.GetString("MainToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个单词在文本中多次出现，你是否想替换全部的单词实例？ 的本地化字符串。
        /// </summary>
        internal static string MoreThanOnceMessage {
            get {
                return ResourceManager.GetString("MoreThanOnceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        internal static string MoveCommand {
            get {
                return ResourceManager.GetString("MoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有发现错误. 的本地化字符串。
        /// </summary>
        internal static string NoSpellingMistakes {
            get {
                return ResourceManager.GetString("NoSpellingMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (没有建议) 的本地化字符串。
        /// </summary>
        internal static string NoSuggestions {
            get {
                return ResourceManager.GetString("NoSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入自定义颜色的16进制值: 的本地化字符串。
        /// </summary>
        internal static string PromptColor {
            get {
                return ResourceManager.GetString("PromptColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设计模式 的本地化字符串。
        /// </summary>
        internal static string RadEditorDesignMode {
            get {
                return ResourceManager.GetString("RadEditorDesignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML模式 的本地化字符串。
        /// </summary>
        internal static string RadEditorHtmlMode {
            get {
                return ResourceManager.GetString("RadEditorHtmlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览模式 的本地化字符串。
        /// </summary>
        internal static string RadEditorPreviewMode {
            get {
                return ResourceManager.GetString("RadEditorPreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请不要删除本字串. RadEditor控件同通检查过这项定义来判断App_GlobalResources中是否存在必需的外部资源文件. 的本地化字符串。
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整对象大小 的本地化字符串。
        /// </summary>
        internal static string ResizeCommand {
            get {
                return ResourceManager.GetString("ResizeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置Html 的本地化字符串。
        /// </summary>
        internal static string SetHtml {
            get {
                return ResourceManager.GetString("SetHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示工具条 的本地化字符串。
        /// </summary>
        internal static string ShowToolbarTooltip {
            get {
                return ResourceManager.GetString("ShowToolbarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拼写检查结束 的本地化字符串。
        /// </summary>
        internal static string SpellCheckComplete {
            get {
                return ResourceManager.GetString("SpellCheckComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成拼写检查 的本地化字符串。
        /// </summary>
        internal static string SpellCheckEnd {
            get {
                return ResourceManager.GetString("SpellCheckEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新拼写 的本地化字符串。
        /// </summary>
        internal static string SpellingChange {
            get {
                return ResourceManager.GetString("SpellingChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在进行拼写检查... 的本地化字符串。
        /// </summary>
        internal static string SpellingInProgress {
            get {
                return ResourceManager.GetString("SpellingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在拼写检查. 拼写错误的单词用黄色的背景色显示. 的本地化字符串。
        /// </summary>
        internal static string SpellingMode {
            get {
                return ResourceManager.GetString("SpellingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表格 的本地化字符串。
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表格工具栏 的本地化字符串。
        /// </summary>
        internal static string TableToolbar {
            get {
                return ResourceManager.GetString("TableToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择表格再设置其属性 的本地化字符串。
        /// </summary>
        internal static string TableWarning {
            get {
                return ResourceManager.GetString("TableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RadEditor工具条 的本地化字符串。
        /// </summary>
        internal static string ToolbarCaption {
            get {
                return ResourceManager.GetString("ToolbarCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mozilla/Netscape浏览器不支持该工具项. 的本地化字符串。
        /// </summary>
        internal static string ToolNotSupportedByNetscape {
            get {
                return ResourceManager.GetString("ToolNotSupportedByNetscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入中... 的本地化字符串。
        /// </summary>
        internal static string Typing {
            get {
                return ResourceManager.GetString("Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在拼写检查模式中不能执行执行Undo操作，请先完成拼写检查操作。 的本地化字符串。
        /// </summary>
        internal static string UndoDisabledMessage {
            get {
                return ResourceManager.GetString("UndoDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+C拷贝 的本地化字符串。
        /// </summary>
        internal static string UseCtrlC {
            get {
                return ResourceManager.GetString("UseCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+V粘帖 的本地化字符串。
        /// </summary>
        internal static string UseCtrlV {
            get {
                return ResourceManager.GetString("UseCtrlV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+X剪切 的本地化字符串。
        /// </summary>
        internal static string UseCtrlX {
            get {
                return ResourceManager.GetString("UseCtrlX", resourceCulture);
            }
        }
    }
}
