//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tools {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tools() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Tools", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于RadEditor控件 的本地化字符串。
        /// </summary>
        internal static string AboutDialog {
            get {
                return ResourceManager.GetString("AboutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置绝对位置 的本地化字符串。
        /// </summary>
        internal static string AbsolutePosition {
            get {
                return ResourceManager.GetString("AbsolutePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基于AJAX拼写检查 的本地化字符串。
        /// </summary>
        internal static string AjaxSpellCheck {
            get {
                return ResourceManager.GetString("AjaxSpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用CSS类 的本地化字符串。
        /// </summary>
        internal static string ApplyClass {
            get {
                return ResourceManager.GetString("ApplyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景颜色 的本地化字符串。
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑体 的本地化字符串。
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部小写 的本地化字符串。
        /// </summary>
        internal static string ConvertToLower {
            get {
                return ResourceManager.GetString("ConvertToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部大写 的本地化字符串。
        /// </summary>
        internal static string ConvertToUpper {
            get {
                return ResourceManager.GetString("ConvertToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拷贝 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小字体 的本地化字符串。
        /// </summary>
        internal static string DecreaseSize {
            get {
                return ResourceManager.GetString("DecreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除单元格 的本地化字符串。
        /// </summary>
        internal static string DeleteCell {
            get {
                return ResourceManager.GetString("DeleteCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除列 的本地化字符串。
        /// </summary>
        internal static string DeleteColumn {
            get {
                return ResourceManager.GetString("DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除行 的本地化字符串。
        /// </summary>
        internal static string DeleteRow {
            get {
                return ResourceManager.GetString("DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除表格 的本地化字符串。
        /// </summary>
        internal static string DeleteTable {
            get {
                return ResourceManager.GetString("DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档管理器 的本地化字符串。
        /// </summary>
        internal static string DocumentManager {
            get {
                return ResourceManager.GetString("DocumentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找并替换 的本地化字符串。
        /// </summary>
        internal static string FindAndReplace {
            get {
                return ResourceManager.GetString("FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash管理器 的本地化字符串。
        /// </summary>
        internal static string FlashManager {
            get {
                return ResourceManager.GetString("FlashManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体名称 的本地化字符串。
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前景色 的本地化字符串。
        /// </summary>
        internal static string ForeColor {
            get {
                return ResourceManager.GetString("ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 段落格式 的本地化字符串。
        /// </summary>
        internal static string FormatBlock {
            get {
                return ResourceManager.GetString("FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式化代码块 的本地化字符串。
        /// </summary>
        internal static string FormatCodeBlock {
            get {
                return ResourceManager.GetString("FormatCodeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式化Stripper 的本地化字符串。
        /// </summary>
        internal static string FormatStripper {
            get {
                return ResourceManager.GetString("FormatStripper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageManager 的本地化字符串。
        /// </summary>
        internal static string ImageManager {
            get {
                return ResourceManager.GetString("ImageManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Map编辑器 的本地化字符串。
        /// </summary>
        internal static string ImageMapDialog {
            get {
                return ResourceManager.GetString("ImageMapDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增大字号 的本地化字符串。
        /// </summary>
        internal static string IncreaseSize {
            get {
                return ResourceManager.GetString("IncreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加缩进 的本地化字符串。
        /// </summary>
        internal static string Indent {
            get {
                return ResourceManager.GetString("Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入Anchor标签 的本地化字符串。
        /// </summary>
        internal static string InsertAnchor {
            get {
                return ResourceManager.GetString("InsertAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从左侧插入列 的本地化字符串。
        /// </summary>
        internal static string InsertColumnLeft {
            get {
                return ResourceManager.GetString("InsertColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从右侧插入列 的本地化字符串。
        /// </summary>
        internal static string InsertColumnRight {
            get {
                return ResourceManager.GetString("InsertColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入自定义链接 的本地化字符串。
        /// </summary>
        internal static string InsertCustomLink {
            get {
                return ResourceManager.GetString("InsertCustomLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入日期 的本地化字符串。
        /// </summary>
        internal static string InsertDate {
            get {
                return ResourceManager.GetString("InsertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入Email链接 的本地化字符串。
        /// </summary>
        internal static string InsertEmailLink {
            get {
                return ResourceManager.GetString("InsertEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按扭 的本地化字符串。
        /// </summary>
        internal static string InsertFormButton {
            get {
                return ResourceManager.GetString("InsertFormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多选框 的本地化字符串。
        /// </summary>
        internal static string InsertFormCheckbox {
            get {
                return ResourceManager.GetString("InsertFormCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单元素 的本地化字符串。
        /// </summary>
        internal static string InsertFormElement {
            get {
                return ResourceManager.GetString("InsertFormElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单 的本地化字符串。
        /// </summary>
        internal static string InsertFormForm {
            get {
                return ResourceManager.GetString("InsertFormForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        internal static string InsertFormHidden {
            get {
                return ResourceManager.GetString("InsertFormHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string InsertFormPassword {
            get {
                return ResourceManager.GetString("InsertFormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单选框 的本地化字符串。
        /// </summary>
        internal static string InsertFormRadio {
            get {
                return ResourceManager.GetString("InsertFormRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string InsertFormReset {
            get {
                return ResourceManager.GetString("InsertFormReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下拉框 的本地化字符串。
        /// </summary>
        internal static string InsertFormSelect {
            get {
                return ResourceManager.GetString("InsertFormSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        internal static string InsertFormSubmit {
            get {
                return ResourceManager.GetString("InsertFormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框 的本地化字符串。
        /// </summary>
        internal static string InsertFormText {
            get {
                return ResourceManager.GetString("InsertFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本区 的本地化字符串。
        /// </summary>
        internal static string InsertFormTextarea {
            get {
                return ResourceManager.GetString("InsertFormTextarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组合框 的本地化字符串。
        /// </summary>
        internal static string InsertGroupbox {
            get {
                return ResourceManager.GetString("InsertGroupbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平标尺 的本地化字符串。
        /// </summary>
        internal static string InsertHorizontalRule {
            get {
                return ResourceManager.GetString("InsertHorizontalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string InsertOrderedList {
            get {
                return ResourceManager.GetString("InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新段落 的本地化字符串。
        /// </summary>
        internal static string InsertParagraph {
            get {
                return ResourceManager.GetString("InsertParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从上方插入行 的本地化字符串。
        /// </summary>
        internal static string InsertRowAbove {
            get {
                return ResourceManager.GetString("InsertRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从下方插入行 的本地化字符串。
        /// </summary>
        internal static string InsertRowBelow {
            get {
                return ResourceManager.GetString("InsertRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入代码片 的本地化字符串。
        /// </summary>
        internal static string InsertSnippet {
            get {
                return ResourceManager.GetString("InsertSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入符号 的本地化字符串。
        /// </summary>
        internal static string InsertSymbol {
            get {
                return ResourceManager.GetString("InsertSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入表格 的本地化字符串。
        /// </summary>
        internal static string InsertTable {
            get {
                return ResourceManager.GetString("InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入时间 的本地化字符串。
        /// </summary>
        internal static string InsertTime {
            get {
                return ResourceManager.GetString("InsertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目符号 的本地化字符串。
        /// </summary>
        internal static string InsertUnorderedList {
            get {
                return ResourceManager.GetString("InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斜体 的本地化字符串。
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中 的本地化字符串。
        /// </summary>
        internal static string JustifyCenter {
            get {
                return ResourceManager.GetString("JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两端对齐 的本地化字符串。
        /// </summary>
        internal static string JustifyFull {
            get {
                return ResourceManager.GetString("JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左对齐 的本地化字符串。
        /// </summary>
        internal static string JustifyLeft {
            get {
                return ResourceManager.GetString("JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除对齐 的本地化字符串。
        /// </summary>
        internal static string JustifyNone {
            get {
                return ResourceManager.GetString("JustifyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右对齐 的本地化字符串。
        /// </summary>
        internal static string JustifyRight {
            get {
                return ResourceManager.GetString("JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超链接管理器 的本地化字符串。
        /// </summary>
        internal static string LinkManager {
            get {
                return ResourceManager.GetString("LinkManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体管理器 的本地化字符串。
        /// </summary>
        internal static string MediaManager {
            get {
                return ResourceManager.GetString("MediaManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平合并单元格 的本地化字符串。
        /// </summary>
        internal static string MergeColumns {
            get {
                return ResourceManager.GetString("MergeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垂直合并单元格 的本地化字符串。
        /// </summary>
        internal static string MergeRows {
            get {
                return ResourceManager.GetString("MergeRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块管理器 的本地化字符串。
        /// </summary>
        internal static string ModuleManager {
            get {
                return ResourceManager.GetString("ModuleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 减少缩进 的本地化字符串。
        /// </summary>
        internal static string Outdent {
            get {
                return ResourceManager.GetString("Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面属性 的本地化字符串。
        /// </summary>
        internal static string PageProperties {
            get {
                return ResourceManager.GetString("PageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘帖 的本地化字符串。
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘帖为Html格式 的本地化字符串。
        /// </summary>
        internal static string PasteAsHtml {
            get {
                return ResourceManager.GetString("PasteAsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从Word粘帖 的本地化字符串。
        /// </summary>
        internal static string PasteFromWord {
            get {
                return ResourceManager.GetString("PasteFromWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从Word粘帖，去除字体和大小的设置 的本地化字符串。
        /// </summary>
        internal static string PasteFromWordNoFontsNoSizes {
            get {
                return ResourceManager.GetString("PasteFromWordNoFontsNoSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘帖为Plain Text 的本地化字符串。
        /// </summary>
        internal static string PastePlainText {
            get {
                return ResourceManager.GetString("PastePlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PasteStrip 的本地化字符串。
        /// </summary>
        internal static string PasteStrip {
            get {
                return ResourceManager.GetString("PasteStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际字体大小 的本地化字符串。
        /// </summary>
        internal static string RealFontSize {
            get {
                return ResourceManager.GetString("RealFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重做 的本地化字符串。
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复最后命令 的本地化字符串。
        /// </summary>
        internal static string RepeatLastCommand {
            get {
                return ResourceManager.GetString("RepeatLastCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请不要删除本字串. RadEditor控件同通检查过这项定义来判断App_GlobalResources中是否存在必需的外部资源文件. 的本地化字符串。
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置单元格属性 的本地化字符串。
        /// </summary>
        internal static string SetCellProperties {
            get {
                return ResourceManager.GetString("SetCellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置图像属性 的本地化字符串。
        /// </summary>
        internal static string SetImageProperties {
            get {
                return ResourceManager.GetString("SetImageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置链接属性 的本地化字符串。
        /// </summary>
        internal static string SetLinkProperties {
            get {
                return ResourceManager.GetString("SetLinkProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置表格属性 的本地化字符串。
        /// </summary>
        internal static string SetTableProperties {
            get {
                return ResourceManager.GetString("SetTableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拼写检查 的本地化字符串。
        /// </summary>
        internal static string SpellCheck {
            get {
                return ResourceManager.GetString("SpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 竖直拆分单元格 的本地化字符串。
        /// </summary>
        internal static string SplitCell {
            get {
                return ResourceManager.GetString("SplitCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除线 的本地化字符串。
        /// </summary>
        internal static string StrikeThrough {
            get {
                return ResourceManager.GetString("StrikeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除所有格式 的本地化字符串。
        /// </summary>
        internal static string StripAll {
            get {
                return ResourceManager.GetString("StripAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除CSS格式 的本地化字符串。
        /// </summary>
        internal static string StripCss {
            get {
                return ResourceManager.GetString("StripCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除Font元素 的本地化字符串。
        /// </summary>
        internal static string StripFont {
            get {
                return ResourceManager.GetString("StripFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除Span元素 的本地化字符串。
        /// </summary>
        internal static string StripSpan {
            get {
                return ResourceManager.GetString("StripSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除Word格式 的本地化字符串。
        /// </summary>
        internal static string StripWord {
            get {
                return ResourceManager.GetString("StripWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下标 的本地化字符串。
        /// </summary>
        internal static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上标 的本地化字符串。
        /// </summary>
        internal static string Superscript {
            get {
                return ResourceManager.GetString("Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表格向导 的本地化字符串。
        /// </summary>
        internal static string TableWizard {
            get {
                return ResourceManager.GetString("TableWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板管理器 的本地化字符串。
        /// </summary>
        internal static string TemplateManager {
            get {
                return ResourceManager.GetString("TemplateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悬停所有浮动工具条/模块 的本地化字符串。
        /// </summary>
        internal static string ToggleDocking {
            get {
                return ResourceManager.GetString("ToggleDocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换全屏模式 的本地化字符串。
        /// </summary>
        internal static string ToggleScreenMode {
            get {
                return ResourceManager.GetString("ToggleScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏边框 的本地化字符串。
        /// </summary>
        internal static string ToggleTableBorder {
            get {
                return ResourceManager.GetString("ToggleTableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下划线 的本地化字符串。
        /// </summary>
        internal static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复 的本地化字符串。
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除链接 的本地化字符串。
        /// </summary>
        internal static string Unlink {
            get {
                return ResourceManager.GetString("Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放 的本地化字符串。
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
